name: Upload ETL Script & Trigger Job

on:
  push:
    branches:
      - nandini  # or 'utkarsh' or any target branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # or your region

      - name: Upload Glue script to S3
        run: |
          aws s3 cp glue_jobs/glue_script.py s3://sample1.output/sampleoutput/glue_sample_output/FEC_Data_Processing.py --region us-east-1

      - name: Start Glue Job
        run: |
          aws glue start-job-run --job-name FEC_Data_Processing --region us-east-1
